import React, {FormEvent, useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis} from 'recharts';
import './styles.css';

type Inventory={collected_at:string;manufacturer:string;model:string;serial_number:string;device_type:string;os_name:string;os_version:string;os_build:string;kernel_version:string;last_os_update:string;cpu_vendor:string;cpu_model:string;cpu_physical_cores:number;cpu_logical_processors:number;total_memory_bytes:number;bios_version:string;gpus:{vendor:string;model:string;memory_bytes:number;driver_version:string}[]};
type Device={id:number;name:string;hostname:string;os:string;architecture:string;agent_version:string;last_seen:string|null;status:string;warning_disk_percent:number;critical_disk_percent:number;failed_ports:number;inventory:Inventory|null;metric:null|{cpu_percent:number;memory_percent:number;memory_total:number;memory_used:number;uptime_seconds:number;network_sent:number;network_recv:number};disks:{mountpoint:string;filesystem:string;total:number;used:number;free:number;percent:number}[]};
type PortCheck={id:number;name:string;host:string;port:number;protocol:'tcp'|'udp';timeout_seconds:number;udp_payload:string;expect_response:boolean;enabled:boolean;latest:null|{is_up:boolean;latency_ms:number;error:string}};
type ProcessInfo={pid:number;name:string;memory_bytes:number;collected_at:string};
type ProcessMonitor={id:number;name:string;running:boolean};
type Detail=Device&{history:{recorded_at:string;cpu_percent:number;memory_percent:number}[];port_checks:PortCheck[];processes:ProcessInfo[];process_monitors:ProcessMonitor[]};

const api=async(path:string,options:RequestInit={})=>{const response=await fetch(path,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});if(!response.ok){let message='Request failed';try{message=(await response.json()).detail||message}catch{}throw new Error(message)}return response.status===204?null:response.json()};
const fmtBytes=(value:number)=>{const units=['B','KB','MB','GB','TB'];let index=0;while(value>=1024&&index<units.length-1){value/=1024;index++}return `${value.toFixed(index?1:0)} ${units[index]}`};
const formatDate=(value:unknown,mode:'time'|'full'='full')=>{const date=new Date(value as string);if(Number.isNaN(date.getTime()))return '';return mode==='time'?date.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):date.toLocaleString()};

function Login({onLogin}:{onLogin:()=>void}){const[username,setUsername]=useState('admin');const[password,setPassword]=useState('');const[error,setError]=useState('');async function submit(event:FormEvent){event.preventDefault();setError('');try{await api('/api/auth/login',{method:'POST',body:JSON.stringify({username,password})});onLogin()}catch(reason){setError((reason as Error).message)}}return <main className="login-shell"><section className="login-card"><div className="brand-mark">E</div><p className="eyebrow">EVOLUTION IT SOLUTIONS</p><h1>Infrastructure clarity,<br/>without the noise.</h1><p className="muted">Sign in to your EITS monitoring console.</p><form onSubmit={submit}><label>Username<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" autoFocus/></label>{error&&<p className="error">{error}</p>}<button>Sign in</button></form></section></main>}
function Meter({value}:{value:number}){return <div className="meter"><span style={{width:`${Math.min(100,value)}%`}}/></div>}
function Kpi({label,value}:{label:string;value:number}){return <article className="kpi"><span>{label}</span><strong>{value}</strong></article>}
function Info({label,value}:{label:string;value:string}){return <div className="info-item"><span>{label}</span><strong>{value||'Not available'}</strong></div>}

function Dashboard({logout}:{logout:()=>void}){
  const[data,setData]=useState<{total:number;counts:Record<string,number>;devices:Device[]}|null>(null);const[selected,setSelected]=useState<number|null>(null);const[error,setError]=useState('');
  const load=()=>api('/api/dashboard').then(setData).catch(()=>logout());
  useEffect(()=>{load();const timer=setInterval(load,15000);return()=>clearInterval(timer)},[]);
  async function removeDevice(event:React.MouseEvent,device:Device){event.stopPropagation();if(!confirm(`Remove ${device.name} and all of its monitoring history? This cannot be undone.`))return;try{await api(`/api/devices/${device.id}`,{method:'DELETE'});await load()}catch(reason){setError((reason as Error).message)}}
  if(!data)return <div className="loading">Loading EITS Monitor...</div>;
  if(selected)return <DeviceView id={selected} back={()=>{setSelected(null);load()}}/>;
  return <div className="app"><header><div><p className="eyebrow">EITS MONITOR</p><h1>System overview</h1></div><button className="ghost" onClick={logout}>Sign out</button></header>{error&&<p className="error notice">{error}</p>}<section className="kpis"><Kpi label="Total devices" value={data.total}/><Kpi label="Healthy" value={data.counts.healthy}/><Kpi label="Warning" value={data.counts.warning}/><Kpi label="Critical" value={data.counts.critical}/><Kpi label="Offline" value={data.counts.offline}/></section><section><div className="section-title"><div><p className="eyebrow">LIVE INVENTORY</p><h2>Monitored devices</h2></div><span className="muted">Refreshes every 15 seconds</span></div><div className="device-grid">{data.devices.map(device=>{const inventory=device.inventory;return <article className="device-card" key={device.id} onClick={()=>setSelected(device.id)}><div className="device-head"><div><h3>{device.name}</h3><p>{device.hostname||'Awaiting hostname'} · {inventory?.os_name||device.os}{inventory?.os_version?` ${inventory.os_version}`:''}</p></div><div className="card-actions"><span className={`status ${device.status}`}>{device.status}</span><button className="danger compact" onClick={event=>removeDevice(event,device)} title="Remove server">Remove</button></div></div><div className="inventory-strip"><div><span>Processor</span><strong>{inventory?.cpu_model||'Inventory pending'}</strong><small>{inventory?`${inventory.cpu_physical_cores} cores / ${inventory.cpu_logical_processors} threads`:'—'}</small></div><div><span>OS update</span><strong>{inventory?.last_os_update||'Not detected'}</strong><small>{inventory?.os_build?`Build ${inventory.os_build}`:device.architecture}</small></div></div><div className="metric-pair"><div><span>CPU usage</span><strong>{device.metric?.cpu_percent.toFixed(1)??'—'}%</strong><Meter value={device.metric?.cpu_percent??0}/></div><div><span>RAM</span><strong>{device.metric?`${fmtBytes(device.metric.memory_used)} / ${fmtBytes(device.metric.memory_total)}`:'—'}</strong><Meter value={device.metric?.memory_percent??0}/></div></div><div className="card-foot"><span>{device.disks.length} disks</span><span>{device.failed_ports} failed checks</span><span>{device.last_seen?formatDate(device.last_seen,'time'):'Never seen'}</span></div></article>})}</div></section></div>
}

function Pager({page,pages,onChange}:{page:number;pages:number;onChange:(page:number)=>void}){if(pages<=1)return null;return <div className="pager"><button className="ghost" disabled={page<=1} onClick={()=>onChange(page-1)}>Previous</button><span>Page {page} of {pages}</span><button className="ghost" disabled={page>=pages} onClick={()=>onChange(page+1)}>Next</button></div>}

function DeviceView({id,back}:{id:number;back:()=>void}){
  const[d,setD]=useState<Detail|null>(null);const[error,setError]=useState('');const[savingCheck,setSavingCheck]=useState(false);const[protocol,setProtocol]=useState<'tcp'|'udp'>('tcp');const[expectResponse,setExpectResponse]=useState(false);const[portSearch,setPortSearch]=useState('');const[portPage,setPortPage]=useState(1);const[processSearch,setProcessSearch]=useState('');const[processPage,setProcessPage]=useState(1);const pageSize=8;
  const load=async()=>{try{setD(await api(`/api/devices/${id}`));setError('')}catch(reason){setError((reason as Error).message)}};
  useEffect(()=>{load();const timer=setInterval(load,15000);return()=>clearInterval(timer)},[id]);
  const filteredPorts=useMemo(()=>d?.port_checks.filter(check=>`${check.name} ${check.host} ${check.port} ${check.protocol}`.toLowerCase().includes(portSearch.toLowerCase()))??[],[d,portSearch]);
  const portPages=Math.max(1,Math.ceil(filteredPorts.length/pageSize));const visiblePorts=filteredPorts.slice((Math.min(portPage,portPages)-1)*pageSize,Math.min(portPage,portPages)*pageSize);
  const filteredProcesses=useMemo(()=>d?.processes.filter(process=>`${process.name} ${process.pid}`.toLowerCase().includes(processSearch.toLowerCase()))??[],[d,processSearch]);
  const processPages=Math.max(1,Math.ceil(filteredProcesses.length/pageSize));const visibleProcesses=filteredProcesses.slice((Math.min(processPage,processPages)-1)*pageSize,Math.min(processPage,processPages)*pageSize);
  const monitoredNames=new Set(d?.process_monitors.map(monitor=>monitor.name.toLowerCase())??[]);
  async function addPort(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const values=new FormData(form);setSavingCheck(true);setError('');try{await api(`/api/devices/${id}/port-checks`,{method:'POST',body:JSON.stringify({name:values.get('name'),host:values.get('host'),port:Number(values.get('port')),protocol,timeout_seconds:Number(values.get('timeout_seconds')||3),udp_payload:String(values.get('udp_payload')||''),expect_response:expectResponse})});form.reset();setProtocol('tcp');setExpectResponse(false);await load()}catch(reason){setError((reason as Error).message)}finally{setSavingCheck(false)}}
  async function removeCheck(checkId:number){if(!confirm('Remove this network check and its history?'))return;try{await api(`/api/devices/${id}/port-checks/${checkId}`,{method:'DELETE'});await load()}catch(reason){setError((reason as Error).message)}}
  async function monitorProcess(name:string){try{await api(`/api/devices/${id}/process-monitors`,{method:'POST',body:JSON.stringify({name})});await load()}catch(reason){setError((reason as Error).message)}}
  async function removeMonitor(monitorId:number){try{await api(`/api/devices/${id}/process-monitors/${monitorId}`,{method:'DELETE'});await load()}catch(reason){setError((reason as Error).message)}}
  async function saveThresholds(event:FormEvent<HTMLFormElement>){event.preventDefault();const values=new FormData(event.currentTarget);try{await api(`/api/devices/${id}/thresholds`,{method:'PATCH',body:JSON.stringify({warning_disk_percent:Number(values.get('warning')),critical_disk_percent:Number(values.get('critical'))})});await load()}catch(reason){setError((reason as Error).message)}}
  if(error&&!d)return <div className="loading">{error}</div>;if(!d)return <div className="loading">Loading device...</div>;
  return <div className="app"><header><div><button className="back" onClick={back}>← Overview</button><p className="eyebrow">DEVICE DETAIL</p><h1>{d.name}</h1><p className="muted">{d.hostname} · {d.os}/{d.architecture} · agent {d.agent_version}</p></div><span className={`status ${d.status}`}>{d.status}</span></header>{error&&<p className="error notice">{error}</p>}
    <section className="kpis"><Kpi label="CPU" value={Math.round(d.metric?.cpu_percent||0)}/><Kpi label="Memory %" value={Math.round(d.metric?.memory_percent||0)}/><Kpi label="Uptime days" value={Math.floor((d.metric?.uptime_seconds||0)/86400)}/><Kpi label="Check failures" value={d.failed_ports}/><Kpi label="Processes" value={d.processes.length}/></section>
    <section className="panel inventory-panel"><div className="panel-heading"><div><h2>Hardware & operating system</h2><p className="muted">Inventory collected {d.inventory?.collected_at?formatDate(d.inventory.collected_at):'not yet'}</p></div></div>{d.inventory?<div className="inventory-grid"><Info label="System" value={[d.inventory.manufacturer,d.inventory.model].filter(Boolean).join(' ')||'Unknown'}/><Info label="Device type" value={d.inventory.device_type}/><Info label="Serial number" value={d.inventory.serial_number||'Not available'}/><Info label="Operating system" value={[d.inventory.os_name,d.inventory.os_version].filter(Boolean).join(' ')}/><Info label="OS build" value={d.inventory.os_build||'Not available'}/><Info label="Latest detected update" value={d.inventory.last_os_update||'Not detected'}/><Info label="Processor" value={d.inventory.cpu_model||'Unknown'}/><Info label="CPU topology" value={`${d.inventory.cpu_physical_cores} cores / ${d.inventory.cpu_logical_processors} threads`}/><Info label="Installed RAM" value={fmtBytes(d.inventory.total_memory_bytes||d.metric?.memory_total||0)}/><Info label="BIOS" value={d.inventory.bios_version||'Not available'}/><Info label="Kernel" value={d.inventory.kernel_version||'Not available'}/><Info label="Graphics" value={d.inventory.gpus?.length?d.inventory.gpus.map(g=>g.model).join(', '):'No GPU detected'}/></div>:<p className="muted">Waiting for the agent to submit its first inventory scan.</p>}</section>
    <section className="panel"><h2>Last hour trend</h2><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={d.history}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="recorded_at" tickFormatter={value=>formatDate(value,'time')}/><YAxis domain={[0,100]}/><Tooltip labelFormatter={value=>formatDate(value)}/><Area type="monotone" dataKey="cpu_percent" fillOpacity={.2}/><Area type="monotone" dataKey="memory_percent" fillOpacity={.1}/></AreaChart></ResponsiveContainer></div></section>
    <div className="two-col"><section className="panel"><h2>Disks</h2>{d.disks.map(disk=><div className="disk" key={disk.mountpoint}><div><strong>{disk.mountpoint}</strong><span>{fmtBytes(disk.free)} free of {fmtBytes(disk.total)}</span></div><b>{disk.percent.toFixed(1)}%</b><Meter value={disk.percent}/></div>)}<form className="inline-form" onSubmit={saveThresholds}><input name="warning" type="number" defaultValue={d.warning_disk_percent}/><input name="critical" type="number" defaultValue={d.critical_disk_percent}/><button>Save thresholds</button></form></section>
      <section className="panel"><div className="panel-heading"><div><h2>Network checks</h2><p className="muted">{filteredPorts.length} TCP/UDP checks</p></div><input className="section-search" value={portSearch} onChange={event=>{setPortSearch(event.target.value);setPortPage(1)}} placeholder="Search checks..."/></div>{visiblePorts.map(check=><div className="port" key={check.id}><div><strong>{check.name} <small className="protocol-badge">{check.protocol.toUpperCase()}</small></strong><span>{check.host}:{check.port}{check.protocol==='udp'&&check.expect_response?' · response required':''}</span></div><span className={`status ${check.latest?.is_up?'healthy':check.latest?'critical':'unknown'}`}>{check.latest?check.latest.is_up?'up':'down':'pending'}</span><button className="danger" onClick={()=>removeCheck(check.id)} aria-label={`Delete ${check.name}`}>×</button></div>)}{!visiblePorts.length&&<p className="empty">No network checks match your search.</p>}<Pager page={Math.min(portPage,portPages)} pages={portPages} onChange={setPortPage}/>
      <form className="port-form network-check-form" onSubmit={addPort}><input name="name" placeholder="Service name" required/><input name="host" placeholder="192.0.2.10" required/><input name="port" type="number" min="1" max="65535" placeholder="443" required/><select name="protocol" value={protocol} onChange={event=>setProtocol(event.target.value as 'tcp'|'udp')}><option value="tcp">TCP</option><option value="udp">UDP</option></select><input name="timeout_seconds" type="number" min="1" max="30" defaultValue="3" title="Timeout seconds"/>{protocol==='udp'&&<><input name="udp_payload" placeholder="Optional UDP payload"/><label className="check-option"><input type="checkbox" checked={expectResponse} onChange={event=>setExpectResponse(event.target.checked)}/>Require response</label></>}<button disabled={savingCheck}>{savingCheck?'Adding...':'Add check'}</button></form></section></div>
    <section className="panel process-panel"><div className="panel-heading"><div><h2>Process monitoring</h2><p className="muted">Choose running processes that must remain available</p></div><input className="section-search" value={processSearch} onChange={event=>{setProcessSearch(event.target.value);setProcessPage(1)}} placeholder="Search name or PID..."/></div>
      <div className="monitor-strip">{d.process_monitors.length?d.process_monitors.map(monitor=><div className="monitor-chip" key={monitor.id}><span className={`state-dot ${monitor.running?'up':'down'}`}/><strong>{monitor.name}</strong><small>{monitor.running?'Running':'Not running'}</small><button className="danger" onClick={()=>removeMonitor(monitor.id)}>×</button></div>):<p className="empty">No processes selected for monitoring.</p>}</div>
      <div className="process-table"><div className="process-row process-head"><span>Process</span><span>PID</span><span>Memory</span><span>Action</span></div>{visibleProcesses.map(process=><div className="process-row" key={`${process.pid}-${process.name}`}><strong>{process.name}</strong><span>{process.pid}</span><span>{process.memory_bytes?fmtBytes(process.memory_bytes):'—'}</span><button className={monitoredNames.has(process.name.toLowerCase())?'ghost':'compact'} disabled={monitoredNames.has(process.name.toLowerCase())} onClick={()=>monitorProcess(process.name)}>{monitoredNames.has(process.name.toLowerCase())?'Monitored':'Monitor'}</button></div>)}</div>{!visibleProcesses.length&&<p className="empty">No process inventory received or no matches found.</p>}<Pager page={Math.min(processPage,processPages)} pages={processPages} onChange={setProcessPage}/>
    </section>
  </div>
}

function App(){const[auth,setAuth]=useState<boolean|null>(null);useEffect(()=>{api('/api/auth/me').then(()=>setAuth(true)).catch(()=>setAuth(false))},[]);if(auth===null)return <div className="loading">Starting EITS Monitor...</div>;if(!auth)return <Login onLogin={()=>setAuth(true)}/>;return <Dashboard logout={async()=>{await api('/api/auth/logout',{method:'POST'});setAuth(false)}}/>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
